# -*- coding: utf-8 -*-
"""homework_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tGSZdCyp0XDKMt5FJhcPL3IJLyMa3S0H

**МНЕ СДЕЛАТЬ:**


1.   Выписать инф-ю по try
2.   Выписать информацию по ф-ям и методам в питоне (разница исп-я, к кому примен-ся)
3.   Выписать типы данных + осн-е методы, способы задачи объекта и пр.
4.   Метод get!!!
5.   Метод sort (в части задания сортировки)
"""

import requests
import json
from collections import defaultdict
from typing import Any, Callable
response = requests.get("https://jsonplaceholder.typicode.com/todos")

"""Делаем запрос к https://jsonplaceholder.typicode.com/todos, во всех задачах далее будем работать с полученным json.

"""

# ✅
# Выведите общее количество задач
# (элементов списка).
response_json = response.json()
print(response_json)

# ✅
# Найдите и выведите все уникальные идентификаторы пользователей (userId), встречающиеся в списке.
my_list = []
for i in response_json:
  my_list.append(i['userId'])

print(set(my_list))

# ✅
# Подсчитайте, сколько задач у каждого пользователя. Результат представьте в виде словаря: {userId: количество}.
# ‼️Попробовать снова через 5 дня, так как искала помощи в ГПТ !!!
tasks_count = {}

for i in response_json:
  user_id = i['userId']
  if user_id in tasks_count:
    tasks_count[user_id] += 1
  else:
    tasks_count[user_id] = 1

print(tasks_count)

# ✅
# Выведите все задачи, у которых поле completed равно True
count_complited_tasks = []

for i in response_json:
  if i['completed'] == True:
    count_complited_tasks.append(i)

print(count_complited_tasks)

# ✅
# Напечатайте список всех заголовков (title) задач.
title_list = []

for i in response_json:
  title_list.append(i['title'])

print(title_list)

# ✅
# Выведите заголовки задач для пользователя с userId = 1.

first_user_titles = []

for i in response_json:
  if i['userId'] == 1:
    first_user_titles.append(i['title'])

print(first_user_titles)

# ✅
#Найдите задачу с id = 2 и выведите её полное содержимое.
second_task= []

for i in response_json:
  if i['id'] == 2:
    second_task.append(i)

print(second_task)

# ✅
# Рассчитайте и выведите процент выполненных задач от общего числа.
completed_tasks = []

for i in response_json:
  if i['completed'] == True:
    completed_tasks.append(i)

delition_res = len(completed_tasks) / len(response_json)

print(delition_res)

# Для каждого userId подсчитайте общее количество задач и количество выполненных. Выведите в читаемом виде.

# Создаем словарь для хранения подсчетов
user_stats = defaultdict(lambda: {'total': 0, 'completed': 0})

    # Проходим по всем задачам и собираем статистику
for i in response_json:
    user_id = i['userId']
    user_stats[user_id]['total'] += 1
    if i['completed']:
        user_stats[user_id]['completed'] += 1

user_stats

# ✅
# Создайте новый список, содержащий только словари с ключами id и title для каждой задачи.

dict_for_tasks = []
for i in response_json:
  proba = [{'id': i['id'], 'title': i['title']}]
  dict_for_tasks.append(proba)
print(dict_for_tasks)
  #proba.append(i['id'])

# ✅
# Найдите задачу с самым длинным заголовком (по количеству символов). Выведите её id, title и длину.

max_title = max(i['title'] for i in response_json)
print(max_title)

# ✅
# Выведите все задачи, в заголовке которых встречается слово "aut" (регистронезависимо).
selected_tasks = []

for i in title_list:
  if 'aut' in i:
    selected_tasks.append(i)

print(selected_tasks)

# ✅
#Преобразуйте список задач в словарь, где ключом является id, а значением – вся задача. Проверьте поиск по id из такого словаря.
new_dict = []

for i in response_json:
  new_value = {'id': i['id'], 'value': i}
  new_dict.append(new_value)
print(new_dict)

new_dict['id'] == '5'

# ✅
#Проверьте, есть ли в списке задача с id = 5.

for i in response_json:
  if i['id'] == 5:
    print(i)

# ✅
#Для задачи с определённым id (например, 2) измените поле completed на противоположное (True → False, False → True). Выведите обновлённую задачу.

def complited_status_change(x):
  changed_row = ()
  for i in response_json:
    if i['id'] == x:
      i['completed'] = not i['completed']
      changed_row = i
  return(changed_row)

print(response_json[5], complited_status_change(5))

# ✅
# Создайте новую задачу (словарь) с новым id (следующим после максимального), произвольным userId, заголовком и completed = False. Добавьте её в список и выведите обновлённый список.

max_task_id = max(i['id'] for i in response_json)
max_task_id += 1
new_task = {'userId': 1, 'id': max_task_id, 'title': 'lscnslclwacmwla cjqanlc waj', 'completed': False}

response_json.append(new_task)

# ✅
# Удалите из списка задачу с указанным id. Проверьте, что она действительно удалена.

def task_deletion(x):
  for i in response_json:
    if i['id'] == x:
      response_json.remove(i)

sldnsldn = task_deletion(201)
print(response_json)

# Создайте два списка: один содержит только выполненные задачи, другой – только невыполненные.

def dictionary_creation():
  completed_tasks_dict = []
  uncompleted_tasks_dict = []

  for i in response_json:
    if i['completed'] == True:
      completed_tasks_dict.append(i)
    elif i['completed'] == False:
      uncompleted_tasks_dict.append(i)
  return completed_tasks_dict, uncompleted_tasks_dict

dictionary_creation()

# Найдите все задачи, у которых длина заголовка меньше 10 символов (или заголовок пустой).
# Но таких же вроде нет....... или есть пустые???
shorty_tasks = []

for i in response_json:
  if len(i['title']) <= 20:
    shorty_tasks.append(i)

print(shorty_tasks)

# Напишите функцию, которая возвращает список задач, отсортированных по длине заголовка (от коротких к длинным).

response_json.sort(key = lambda x: len(x['title']))

print(response_json)

# Подсчитайте общее количество символов во всех заголовках задач.

lens_sum = sum(len(i['title']) for i in response_json)
print(lens_sum)

# Выведите первые 3 задачи с самыми длинными заголовками.

response_json.sort(key = lambda x: len(x['title']), reverse=True)

print(response_json[0:2])

"""# Анализ цен на товары

✅
**Задача 1: Загрузка данных из JSON**

Напишите функцию load_products(filename), которая:

Принимает имя JSON-файла

Загружает данные и возвращает список товаров

Обрабатывает возможные ошибки (файл не найден, неверный JSON)
"""

def load_products(filename):
  try:
    with open(filename, 'r') as file:
      test_dataset = json.load(file)
      return(test_dataset)
  except FileNotFoundError:
    print(f"Ошибка: Файл '{filename}' не найден.")
    return []
  except json.JSONDecodeError:
    print(f"Ошибка: У файла '{filename}' неверный формат.")
    return []
  except Exception as e:
    print(f"Проищошла ошибка {e}")
    return []

test_json_load = load_products('test_dataset')
print(test_json_load)

"""✅
**Задача 2: Фильтрация товаров с лямбда-функциями**

Напишите функцию filter_products(products, *filters), которая:

*   Принимает список товаров и произвольное количество лямбда-функций через *args
*   Последовательно применяет все фильтры к товарам
*   Возвращает отфильтрованный список Пример использования:
```
# Найти все товары в наличии с ценой меньше 30000
in_stock = lambda p: p['in_stock']
price_filter = lambda p: p['price'] < 30000

result = filter_products(products, in_stock, price_filter)
```
"""

products_test = [
    {
        "id": 1,
        "name": "Ноутбук ASUS",
        "category": "electronics",
        "price": 45000,
        "old_price": 50000,
        "in_stock": True,
        "rating": 4.5
    },
    {
        "id": 2,
        "name": "Смартфон Xiaomi",
        "category": "electronics",
        "price": 25000,
        "old_price": 27000,
        "in_stock": True,
        "rating": 4.7
    },
    {
        "id": 3,
        "name": "Наушники Sony",
        "category": "audio",
        "price": 5000,
        "old_price": 6000,
        "in_stock": False,
        "rating": 4.3
    },
    {
        "id": 4,
        "name": "Планшет Samsung",
        "category": "electronics",
        "price": 30000,
        "old_price": 32000,
        "in_stock": True,
        "rating": 4.4
    },
    {
        "id": 5,
        "name": "Колонка JBL",
        "category": "audio",
        "price": 4000,
        "old_price": 4500,
        "in_stock": True,
        "rating": 4.6
    }
]

in_stock = lambda p: p['in_stock']
price_filter = lambda p: p['price'] < 30000
category_filter = lambda a: a['category'] == 'electronics'


def filter_products(products, *filters):
  dataset = products

  for i in filters:
    filtered_products = filter(i, dataset)
    print(list(filtered_products))

testtttt = filter_products(products_test, in_stock, price_filter, category_filter)

print(testtttt)

"""✅**Задача 3: Поиск скидок**

Напишите функцию find_discounts(products, **criteria), которая:

*   Принимает список товаров
*   Через **kwargs принимает критерии поиска: min_discount, max_price, category
*   Находит товары, у которых есть скидка (old_price > price)
*   Возвращает список товаров со скидками, отсортированный по размеру скидки

Пример:


```
# discounts = find_discounts(
    products,
    min_discount=10,  # минимальная скидка в процентах
    max_price=40000,  # максимальная цена
    category="electronics"
)
```


"""

##метод get используется для получения значений из словаря
##Метод get() в Python — это безопасный способ получения значения из словаря (dict) по ключу. В отличие от доступа через скобки dict[key],
##метод get(key, default) не вызывает ошибку KeyError, если ключ отсутствует, а возвращает None или заданное значение по умолчанию, предотвращая сбои программы

##sort - встроенный метод списков, который упорядочивает их элементы (числа, строки) по возрастанию или убыванию (с reverse=True)
## Для сортировки по определнному шаблону необходимо использовать аргуемент key и указать в нем функцию!!
##https://docs.python.org/3/howto/sorting.html


def find_discounts(products, **criteria):

  dataset = products
  min_discount = criteria.get('min_discount')
  max_price = criteria.get('max_price')
  category = criteria.get('category')

  discounted_products = []

  for i in dataset:
    if i['old_price'] > i['price']:
      discount_percentage = round((i['old_price'] - i['price']) / i['old_price'] * 100)
      if discount_percentage >= min_discount and i['price'] <= max_price and i['category'] == category:
        i['discount_percent'] = discount_percentage
        discounted_products.append(i)
        discounted_products.sort(key = lambda x: x['discount_percent'])
  return discounted_products

jnlcnalc = find_discounts(products_test, min_discount = 5, max_price = 6000, category = 'audio')
 print(jnlcnalc)

"""**Задача 4: Статистика по категориям**

Напишите функцию category_stats(products, *categories) которая:

1.   Принимает список товаров и названия категорий через *args
2.   Для каждой категории считает:

*   Количество товаров
*   Среднюю цену
*   Минимальную и максимальную цену
*   Общее количество товаров в наличии
3.   Возвращает словарь со статистикой
"""

def category_stats(products, categories):
  produts_dataset = products
  right_goods = []
  category = categories

  for i in produts_dataset:
    if i['category'] == category:
      right_goods.append(i)
      for i in right_goods:
        quantity = sum(1 for i in right_goods) # counter += 1 ##Почему выводит на 1 больше??
        avg_price = round(sum(i['price'] for i in right_goods) / len(right_goods), 2)
        min_price = min(i['price'] for i in right_goods)
        max_price = max(i['price'] for i in right_goods)
        available_goods = sum(1 for i in right_goods if i["in_stock"])
  results = {"category": category, "goods_amt": quantity, "avg_price": avg_price, "min_price": min_price, "max_price": max_price, "available_goods": available_goods}
  #return(quantity, avg_price, min_price, max_price, available_goods)
  return results

  right_goods = []

sacaqcadd  = category_stats(products_test, 'electronics')
print(sacaqcadd)

"""**Задача 5: Сохранение отчета**

Напишите функцию save_report(products, filename, **options) которая:

1.   Принимает список товаров
2.   Через **kwargs принимает параметры отчета: format (txt/csv), include_discounts, sort_by
3.   Сохраняет отчет в указанный файл
"""

def save_report(products, filename, **options):
  dataset = products
  filename = filename
  format = options.get('format (txt/csv)')
  include_discounts = options.get('include_discounts')
  sort_by = options.get('sort_by')

  with open(filename, 'r') as file:
    file.write()

"""**Задача 6: Основная программа**

Создайте основную функцию analyze_prices(products_file, **settings), которая:

1.   Принимает имя файла с данными
2.   Через **kwargs принимает настройки анализа:

*   categories - какие категории анализировать
*   min_rating - минимальный рейтинг
*   discount_threshold - порог скидки для уведомления
*   report_file - файл для отчета
*   report_format - формат отчета

Функция должна:

*   Загрузить данные из JSON
*   Применить фильтры на основе настроек
*   Найти товары со скидками
*   Посчитать статистику по категориям
*   Сохранить отчет
*   Вернуть словарь с результатами анализа

Пример использования программы


```
# Выбран кодовый формат

# Настройки анализа
settings = {
    'categories': ['electronics', 'audio'],
    'min_rating': 4.0,
    'discount_threshold': 10,
    'report_file': 'price_report.txt',
    'report_format': 'txt',
    'sort_by': 'discount'
}

# Запуск анализа
results = analyze_prices('products.json', **settings)

# Вывод результатов
print(f"Всего товаров: {results['total_products']}")
print(f"Товаров со скидкой: {results['discounted_count']}")
print(f"Средняя скидка: {results['avg_discount']}%")
print(f"Отчет сохранен в {results['report_file']}")
```
Требования к реализации

Обязательно использовать:
*   *args для передачи переменного количества фильтров или категорий
*   **kwargs для передачи настроек в функции
*   Лямбда-функции для фильтрации товаров
*   Работу с JSON-файлами (чтение)
*   Работу с текстовыми файлами (запись отчета)

Функции для реализации:


*   load_products(filename)
*   filter_products(products, *filters)
*   find_discounts(products, **criteria)
*   category_stats(products, *categories)
*   save_report(products, filename, **options)
*   analyze_prices(products_file, **settings)

Ожидаемый результат

Программа должна создавать файл отчета примерно такого содержания:


```
# Выбран кодовый формат
========== ОТЧЕТ О ЦЕНАХ ==========
Дата: 2024-01-15 14:30:45

ВСЕГО ТОВАРОВ: 5
Из них в наличии: 4

КАТЕГОРИЯ electronics:
  Товаров: 3
  Средняя цена: 33333.33 ₽
  Мин цена: 25000 ₽
  Макс цена: 45000 ₽
  В наличии: 3

КАТЕГОРИЯ audio:
  Товаров: 2
  Средняя цена: 4500.00 ₽
  Мин цена: 4000 ₽
  Макс цена: 5000 ₽
  В наличии: 1

ТОВАРЫ СО СКИДКОЙ (более 10%):
1. Ноутбук ASUS
   Цена: 45000 ₽ (было 50000 ₽)
   Скидка: 10.0%
   Категория: electronics

2. Наушники Sony
   Цена: 5000 ₽ (было 6000 ₽)
   Скидка: 16.7%
   Категория: audio
   (НЕТ В НАЛИЧИИ)

===================================
```
"""

