# -*- coding: utf-8 -*-
"""homework_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iQ7z2aZPlTpd4zwFFELvsPgMjdAB5DLL
"""

import re
import os.path

"""1. Функция проверки длины:

Если длина пароля меньше 6 — вернуть "Слишком короткий".

Если от 6 до 10 — вернуть "Средняя длина".

Если больше 10 — вернуть "Длинный".
"""

def length_check (x) -> None:
  length_test = len(x)

  if length_test <6:
    print(f"Слишком короткий")
  elif length_test >= 6 and 10 > length_test:
    print(f"Средняя длина")
  elif length_test >= 10:
    print(f"Длинный")
## МНЕ: Как записать не через много принтов, условно верни запись, а в конце ретерн запись??

test_1 = length_check('мпяпыкирчирчпич')

"""2. Функция проверки наличия цифр:

Проверяет, есть ли в строке хотя бы одна цифра. Какой возврат у функции - реши самостоятельно. Тут можно заюзать цикл и метод строк isdigit() либо! regex при желании



МНЕ: логика по SQL - тип регулярка на убирание всех НЕ цифр, а-ля regexp_replase(column, '[^\d]', '', 'g')

 isdigit() - проверяет состоит ли вся строка из цифр, а не вхождения (т.е в 0 упадут как "пповал 5" так и "аррао", а в 1 только "12345" - не удобно, легче регуляркой
"""

str_for_test = 'праллбвсд'
print(str_for_test.isdigit())

text = 'Чтоб вас драли 5 раз 2-ды'
test_check = re.findall('\d+', text)
print(len(test_check))
## как в sql обозн-е дигитов, НО маркер 'g' задается через +

def len_check(y):
  length_test_2 = len(re.findall('\d+', y))

  if length_test_2 > 0:
    print(f"str consists digit")
  else:
    print(f"str doesn't consist digit")

test_2 = len_check('Хочу зп 1005000000 млн')

test_2_2 = len_check('Не хочу работать')

"""3. Функция проверки наличия заглавных букв:

Проверяет, есть ли в строке хотя бы одна заглавная буква. Какой возврат у функции - реши самостоятельно. Тут можно заюзать цикл и метод строк isupper() либо! regex при желании

"""

find_upper = 'Сердце Дышит!Heart!'
print(re.findall('([A-Z]|[А-Я])+', find_upper))

def find_upper_func (stringa):
  length_test_3 = len(re.findall('([A-Z]|(А-Я))+', stringa))

  if length_test_3 > 0:
    print(f"str consists upper")
  else:
    print(f"str doesn't consist upper")

test_3_1 = find_upper_func('dkhcfwbDFG ОЛлиа')
test_3_2 = find_upper_func('kknd пшнх 1!!аф')
print(test_3_1, test_3_2)

"""4. Главная функция оценки надежности.

Внутри она должна:

Вызвать функцию проверки длины и сохранить результат.
Проверить наличие цифр и заглавных букв с помощью соответствующих функций.
Вывести итог:
Если пароль "Слишком короткий" — сразу сообщить об этом и не проверять дальше.
Если длина нормальная (средняя или длинная), и есть и цифры, и заглавные буквы — написать: "Отлично! Пароль ... , содержит цифры и заглавные буквы. Надежный пароль!".
Если длина нормальная, но нет ни цифр, ни заглавных — написать: "Пароль ... , но не содержит ни цифр, ни заглавных букв. Слишком простой.".
Если не хватает только цифр — написать: "Пароль ... , но не содержит цифр. Добавьте хотя бы одну цифру.".
Если не хватает только заглавных букв — написать: "Пароль ... , но не содержит заглавных букв. Добавьте хотя бы одну заглавную букву.".
В этом пункте тебе нужно в теле функции вызвать другие функции, это изи:

def a() -> int:
    print()
    
def b() -> int:
    vyzov_a = a() -- вызвали другую функцию
    return vyzov_a + 2

Сначала проверка длины -> 1-я ф-я

2-я:

---
"""

#гспд помилуй, я потратила час из-за return
def length_func (length_testik) -> str:
  str_length_check = len(length_testik)
  if str_length_check < 6:
    return('короткий')
  elif str_length_check >= 6 and str_length_check < 10:
    return('средней длинны')
  elif str_length_check >= 10:
    return('длинный')

def letters_nmb_check(password)-> str:
    vyzov = length_func(password)
    uppers = len(re.findall('([A-Z]|[А-Я])+', password))
    digits = len(re.findall('\d+', password))

    if length_func(password) == 'короткий':
      print(f'Слишком короткий\n')
    elif uppers > 0 and digits > 0:
      print(f'Отлично! Пароль {vyzov}, содержит цифры и заглавные буквы. Надежный пароль!\n\n')
    elif uppers == 0 and digits == 0:
      print(f'Пароль {vyzov}, но не содержит ни цифр, ни заглавных букв. Слишком простой.\n\n')
    elif uppers > 0 and digits == 0:
      print(f'Пароль {vyzov}, но не содержит цифр. Добавьте хотя бы одну цифру.\n\n')
    elif uppers == 0 and digits > 0:
      print(f'Пароль {vyzov}, но не содержит заглавных букв. Добавьте хотя бы одну заглавную букву.\n\n')


help_me_god = letters_nmb_check('poshlyegonaa')

"""Функции для классификации задач

Функция determine_priority(deadline_days):

Принимает количество дней до дедлайна (целое число).
Возвращает приоритет задачи:

deadline_days < 0 → "Просрочено!"

1 <= deadline_days <= 3 → "Высокий приоритет"

4 <= deadline_days <= 7 → "Средний приоритет"

deadline_days > 7 → "Низкий приоритет"
"""

def determine_priority(deadline_days: int) -> str:
  deadline_days = int(deadline_days)
  if deadline_days <= 0:
    return("Просрочено!")
  elif 1 <= deadline_days <= 3:
    return("Высокий приоритет")
  elif 4 <= deadline_days <= 7:
    return("Средний приоритет")
  elif deadline_days > 7:
    return("Низкий приоритет")

## А что с 0???

deadline_days_test = determine_priority(1)
print(deadline_days_test)

"""Функция get_status_symbol(status):

Принимает статус задачи (строка: "новая", "в работе", "готова").
Возвращает эмодзи или символ для красивого отображения:

"новая" → "🆕"

"в работе" → "⚙️"

"готова" → "✅"

Любое другое значение → "❓"
"""

def get_status_symbol(status: str)-> str:
  if status == 'новая':
    return('🆕')
  elif status == 'в работе':
    return('⚙️')
  elif status == 'готова':
    return('✅')
  else:
    return('❓')

print(get_status_symbol("новая"))

"""Функция save_task(task_name, priority, status_symbol, deadline_days):

Принимает: название задачи, приоритет (из первой функции), символ статуса (из второй функции), и количество дней до дедлайна.

Записывает строку в файл tasks.txt в формате:
Название: Купить подарок | Статус: ⚙️ | Приоритет: Высокий приоритет | Дней до дедлайна: 2

Возвращает True при успехе.
"""

def save_task(task_name:str, priority:str, status_symbol:str, deadline_days:int) -> str:
  file = open("tasks.txt", "a")
  file.write("Название: " + task_name + " | Приоритет: " + priority + " | Статус: " + status_symbol + " | Дней до дедлайна: " + str(deadline_days) + "\n")
  file.close()

proba = save_task('Купить полку', 'Низкий приоритет', '❓', 54)
proba_2 = save_task('Купить шампунь', 'Высокий приоритет', '✅', 2)
proba_3 = save_task('Упаковать подарок', 'Высокий приоритет', '⚙️', 1)
proba_4 = save_task('Убрать квартиру', 'Высокий приоритет', '🆕', 3)
proba_5 = save_task('Выбрать купальник', 'Средний приоритет', '⚙️', 7)
proba_6 = save_task('Купить валюту', 'Высокий приоритет', '✅', 1)
proba_7 = save_task('Поправить pr_positions', 'Низкий приоритет', '🆕', 2)

"""Функция show_tasks_by_priority(priority_filter):

Принимает строку с приоритетом для фильтрации (например, "Высокий приоритет").

Открывает файл tasks.txt для чтения ('r').

Если файла нет — выводит "Список задач пуст."

Если файл есть — читает все строки и выводит только те, где приоритет совпадает с priority_filter.

Считает и выводит количество таких задач.
"""

def show_tasks_by_priority(priority_filter):
  my_list = []

  with open("/content/tasks.txt", "r") as file:
    content = file.readlines()
  if os.path.exists("/content/tasks.txt") is False:
      return("Список задач пуст.")
  else:
    for i in content:
      if priority_filter in i:
        my_list.append(i)
    print(f"Количество задач с таким приоритетом: {len(my_list)}")

test_show_tasks_by_priority = show_tasks_by_priority("Высокий приоритет")

"""Функция count_tasks_by_status():


Открывает файл tasks.txt для чтения.

Создает три счетчика: новые, в работе, готовые.

Проходит по всем строкам, смотрит на статус (эмодзи) и увеличивает соответствующий счетчик.

Выводит статистику:

Статистика задач:

Новые: 3

В работе: 2

Готовые: 5

Всего задач: 10
"""

def count_tasks_by_status():
  new_list = []
  with open("/content/tasks.txt", "r") as file:
    content = file.readlines()
    for i in content:
      if "🆕" in i:
       new_tasks.append(i)

def count_tasks_by_status():
  new_tasks = []
  in_process_tasks = []
  ready_tasks = []
  with open("/content/tasks.txt", "r") as file:
      content = file.readlines()
      for i in content:
        if "🆕" in i:
          new_tasks.append(i)
        elif "⚙️" in i:
          in_process_tasks.append(i)
        elif "✅" in i:
          ready_tasks.append(i)
      all_tasks = len(new_tasks) + len(in_process_tasks) + len(ready_tasks)
      print(f"Новые: {len(new_tasks)} \nВ работе: {len(in_process_tasks)} \nГотовые: {len(ready_tasks)} \nВсего задач: {all_tasks}")

count_tasks_by_status()

"""Функция main():
Выводит меню:
1. Добавить новую задачу
2. Показать все срочные задачи (Высокий приоритет)
3. Показать статистику по статусам
4. Выход

Запрашивает у пользователя выбор (погугли input(), например https://www.w3schools.com/python/ref_func_input.asp). В целом обработка инпута необязательна, можешь просто данные перекидывать в функции, тк этот момент непринципиален.

Использует if/elif/else для обработки:

Если 1:
Запрашивает название задачи.
Запрашивает статус (новая/в работе/готова).
Запрашивает количество дней до дедлайна.
Вызывает determine_priority для определения приоритета.
Вызывает get_status_symbol для получения символа статуса.
Вызывает save_task для сохранения в файл.

Если 2:
Вызывает show_tasks_by_priority с параметром "Высокий приоритет" (и отдельно для "Срочно! (сегодня)", если хотите усложнить).

Если 3:
Вызывает count_tasks_by_status.

Если 4:
Завершает программу.

Иначе:
Выводит "Неверный выбор."
"""

#Умир из-за get_status_symbol (ебаный NoneType, ты это специально, признавайся!)
def main():

  while True:
    menu_message = "МЕНЮ (укажите цифру) \n1. Добавить новую задачу \n2. Показать все срочные задачи (Высокий приоритет)\n3. Показать статистику по статусам\n4. Выход"
    print(menu_message)
    users_choise = input()

    if users_choise == "1":
      print("Введите название задачи:")
      name = str(input())
      print("Введите статус задачи (новая/в работе/готова):")
      status = str(input())
      print("количество дней до дедлайна:")
      dl_days = str(input())

      priority = determine_priority(int(dl_days))
      status_symbol = get_status_symbol(status)

      save_task(name, priority, status_symbol, dl_days)

    elif users_choise == "2":
      show_tasks_by_priority("Высокий приоритет")

    elif users_choise == "3":
      count_tasks_by_status()

    elif users_choise == "4":
      print("До скорого!")
      break

main()

"""# Чтение кода

**№ 1**
"""

def get_age_category(age):
    if age < 0:
        return "Ошибка"
    elif age <= 2:
        return "Младенец"
    elif age <= 12:
        return "Ребенок"
    elif age <= 19:
        return "Подросток"
    elif age <= 35:
        return "Молодой"
    elif age <= 60:
        return "Взрослый"
    else:
        return "Пожилой"

fsksk = get_age_category(5)
print(fsksk)

"""В зависимости от значения возраста присваивается статус:

"Младенец" (с 0 до 2-х)

"Ребенок" (с 3-х до 12)

"Подросток" (с 13 до 19)

"Молодой" (с 20 до 35)

"Взрослый" (с 36 до 60)

"Пожилой" (с 61 и далее)

Для отриц-х - ошибка

**№ 2**
"""

def can_vote(age):
    if age >= 18:
        return "Может голосовать"
    else:
        return "Не может голосовать"

cjdkfls = can_vote(-3)
print(cjdkfls)

"""В зависимости от значения возраста присваивается статус:

"Может голосовать" (с 18 и далее)

"Не может голосовать" (до 18)

Принимает на вход и отриц-е

**№ 3**
"""

def save_to_file(name, age, category, vote_status):
    file = open("people.txt", "a")
    file.write(
        name + " | " + str(age) + " лет | " + category + " | " + vote_status + "\n")
    file.close()
    print("Данные сохранены в файл!")

#file_people = save_to_file("Лена", 26, "Молодой", "Может голосовать")
file_people = save_to_file("Раф", 26, "Молодой", "Может голосовать")

"""Создает файл и записывает в него записи (тавтология, но мне плевать), которые содержат инф-ю об имени человека его возрасте, категории (1-я ф-я) и статусе голосования (2-я функция)

**№ 4**
"""

def show_all_people():
    file = open("people.txt", "r")
    content = file.read()
    if content == "":
        print("Файл пуст")
    else:
        print("=== Все записи ===")
        print(content)
    file.close()

"""Обращается к содержимому созданного ранее файла, при этом если файл пустой (не создан) - выводит "Файл пуст" иначе выводит все записи после создания заголовка в виде надписи "=== Все записи ==="

**№ 5**
"""

def main():
    print("Программа определения возраста")

    while True:
        print("\n1. Добавить человека")
        print("2. Показать всех")
        print("3. Выйти")
        choice = input("Выберите действие: ")

        if choice == "1":
            name = input("Имя: ")
            age = int(input("Возраст: "))

            category = get_age_category(age)

            if category == "Ошибка":
                print("Возраст не может быть отрицательным!")
            else:
                vote = can_vote(age)
                print(name + " - " + category)
                print("Статус голосования: " + vote)
                save_to_file(name, age, category, vote)

        elif choice == "2":
            show_all_people()

        elif choice == "3":
            print("Пока!")
            break
        else:
            print("Неверный выбор")

main()

"""Программа дает на выбор 3 дей-я по умолчанию:

1. "Добавить человека" - можно ввести имнофрмацию об имени и возрасте человека, если ввести цифру 1, далее определится статус и возможность голосовать, а также данные запишутся в файл, далее возвращается в главное меню

2. "Показать всех" - выводит весь список записей, далее возвращается в главное меню

3. "Выйти" - прерывает выполнение программы с выведением фразы "Пока"
"""